name 'ebs_manage'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures ebs_manage'
long_description 'Installs/Configures ebs_manage'
version '0.1.0'
