name 'ebs_manage'
maintainer 'Ilias Bertsimas'
maintainer_email 'ilias.bertsimas@sainsburys.co.uk'
license 'all_rights'
description 'Installs/Configures ebs_manage'
long_description 'Installs/Configures ebs_manage'
version '0.1.0'
